### PR TITLE
IPDK Storage APIs

### PR DESCRIPTION
**Pull request by dandaly**
Signed-off-by: Dan Daly <dan.daly@intel.com>

### CODE REVIEW

**Review by seroyer — APPROVED** [review]

**Review by mestery — COMMENTED** [review]
Would be nice to format this into 80 character lines, this is currently one giant, long line of text.

**Comment by dandaly** [comment]
Just pushed a version that is aligned to 80.

**Review by mestery — APPROVED** [review]

**Review by glimchb — APPROVED** [review]
would be nice to the same PR on IPDK github org as well

**Review by sandersms — APPROVED** [review]

**Comment by mestery** [comment]
> would be nice to the same PR on IPDK github org as well

Good idea! @dandaly can you link the IPDK PR here as well? Thanks!

**Comment by dandaly** [comment]
> > would be nice to the same PR on IPDK github org as well
> 
> Good idea! @dandaly can you link the IPDK PR here as well? Thanks!

Yes once this is approved in the TSC I will add deprecation notices to the code and on the Recipe page and I'll link those back to this thread.

**Comment by mestery** [comment]
Passed TSC vote in the 2022-12-15 meeting.

**Comment by dandaly** [comment]
> would be nice to the same PR on IPDK github org as well

Hi the IPDK PR containing this note is here, this is the Storage specific release for notes for 23.01.  This note will also be bubbled up into the full 23.01 release notes:

https://github.com/ipdk-io/ipdk/pull/334

**Pull request merged**
