### PR TITLE
[storage] Renaming Aio and Null to Volume

### PR DESCRIPTION
**Pull request by glimchb**
- [storage] Renaming Aio and Null to Volume
- [storage] auto-generate protos

### CODE REVIEW

**Comment by artek-koltun** [comment]
Please update the commit msgs
```
b3ae105: [storage] Renaming Aio and Null to Volume

This brings more consistency to the naming of backend

Fixes #304

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
Error: ✖ subject may not be empty
Error: ✖ type may not be empty
fca8c22: [storage] auto-generate protos

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>
Error: ✖ subject may not be empty
Error: ✖ type may not be empty
Error: commitlint failed
```

**Comment by glimchb** [comment]
> Please update the commit msgs

fixed

**Review by artek-koltun — APPROVED** [review]
LGTM

**Review by sandersms — APPROVED** [review]
LGTM

**Pull request merged**
