### PR TITLE
network: Implementation Options for Network API Service

### PR DESCRIPTION
**Pull request by pathreya**
A: Fully Vendor implemented
B: Partly Vendor implemented with SB implementations for popular
   open source entities such as OVS, VPP implemented by OPI rather
   than vendor.
C: Similar to B, but makes the vendor specific code a plugin into
   OPI Service. It can coexist with B.

Signed-off-by: Narayana Prasad <110230547+pathreya@users.noreply.github.com>

### CODE REVIEW

**Comment by pathreya** [comment]
> It would be great if you could convert this to markdown as its easier to review.
@mestery I presume you are looking for the commit message as a markdown file. If so, sure, i will add that.

> or do we build software for DPU and IPU cards. I believe the former is what we need to do first, and let vendors implement the APIs however we want. But I'm curious what you think. Thanks!
The protobufs are needed for sure. Its also beneficial to support popular implementations like OVS, VPP. Vendors are likely to use these implementations and can leverage OPI reference code i feel. I also commented likewise on slack.

**Comment by mestery** [comment]
> > It would be great if you could convert this to markdown as its easier to review.
> 
> @mestery I presume you are looking for the commit message as a markdown file. If so, sure, i will add that.
> 
No, I mean instead of checking in a PDF, which we cannot review, please convert the PDF to a markdown file, which we can review.

> > or do we build software for DPU and IPU cards. I believe the former is what we need to do first, and let vendors
> > implement the APIs however we want. But I'm curious what you think. Thanks!
> 
> The protobufs are needed for sure. Its also beneficial to support popular implementations like OVS, VPP. Vendors are likely to use these implementations and can leverage OPI reference code i feel. I also commented likewise on slack.

It's fine for us to implement a reference implementation, but we will run into the OpenStack Neutron problem. First of all, people will run the reference implementation in production even though we tell them not to. This will lead to complaints that OPI is not stable and ready for production, despite us telling them not to run it in production. Secondly, vendors will use this to say how their OPI implementation is better than the reference implementation. This game is well known in open source, and I'd prefer not to have to fight it here in OPI, despite the group seemingly walking in this direction at the moment.

**Review by mestery — CHANGES_REQUESTED** [review]
Please convert the document from PDF to markdown so we can provide review comments on it. We don't want to check PDF files into the repository.

**Comment by pathreya** [comment]
Hi Kyle
   How do I do that? Is there a tool I should use?
Please note I exported the pdf from draw.io.

Thanks
Prasad


________________________________
From: Kyle Mestery ***@***.***>
Sent: 29 July 2022 21:05
To: opiproject/opi-api ***@***.***>
Cc: Narayana Prasad Raju Athreya ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [opiproject/opi-api] network: Implementation Options for Network API Service (PR #63)

External Email
________________________________

@mestery requested changes on this pull request.

Please convert the document from PDF to markdown so we can provide review comments on it. We don't want to check PDF files into the repository.

**Comment by mestery** [comment]
> Hi Kyle How do I do that? Is there a tool I should use? Please note I exported the pdf from draw.io. Thanks Prasad
> […](#)

If this is simply a diagram, then you should save the file in draw.io as an editable png image with the extension `.drawio.png` to signify that. If it is a document which you saved as PDF, you can use an online conversion tool to convert from PDF to markdown such as [this one](https://pdf2md.morethan.io).

**Comment by pathreya** [comment]
Thanks Kyle. My drawio files has 3 images(3 pages). So I will end up uploading 3 png files. Is that ok?

I will also try out the online tool you suggested.

Thanks
Prasad


________________________________
From: Kyle Mestery ***@***.***>
Sent: 02 August 2022 18:36
To: opiproject/opi-api ***@***.***>
Cc: Narayana Prasad Raju Athreya ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [opiproject/opi-api] network: Implementation Options for Network API Service (PR #63)

External Email
________________________________

Hi Kyle How do I do that? Is there a tool I should use? Please note I exported the pdf from draw.io. Thanks Prasad
…

If this is simply a diagram, then you should save the file in draw.io as an editable png image with the extension .drawio.png to signify that. If it is a document which you saved as PDF, you can use an online conversion tool to convert from PDF to markdown such as this one<https://urldefense.proofpoint.com/v2/url?u=https-3A__pdf2md.morethan.io&d=DwMFaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=RCw0B_bXeBHj8OOlpjUu9zpmdF7sQ401oo770tafM-g&m=klVWiNopC5cFFDDNIZjM8RfO2_VT0QZgg6zbkinL8RuTCCnyJ96vcX-rIhZBzJ2Y&s=Sjd94J_9J3IcuaVDp0vZIIhT9qTSyRDXZldYK6bLMZE&e=>.

**Comment by mestery** [comment]
> Thanks Kyle. My drawio files has 3 images(3 pages). So I will end up uploading 3 png files. Is that ok? I will also try out the online tool you suggested. Thanks Prasad
> […](#)

If you made these using draw.io, please just save them as editable PNG files and check them into the appropriate directory. That way, others can edit them using draw.io and we can version them here. Thanks!

**Review by mestery — APPROVED** [review]
Thanks for the commit! It would be good to provide some context of these diagrams at some point by referencing them in a markdown file somewhere, but approving for now.

**Pull request merged**
