### PR TITLE
feat: resource name IDENTIFIER enforcement

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by glimchb** [comment]
new linter PR to enforce IDENTIFIER is merge https://github.com/googleapis/api-linter/pull/1241
waiting on the new release https://github.com/googleapis/api-linter/releases

**Comment by mardim91** [comment]
The changes to the EVPN GW API looks good to me. You have the green light from my side to merge this when this is needed.

**Comment by glimchb** [comment]
now waiting on https://github.com/docker-multiarch/google-api-linter/tags

**Comment by glimchb** [comment]
> now waiting on https://github.com/docker-multiarch/google-api-linter/tags

released!


now fails on
```
docker run --user=$(id -u):$(id -g) --rm -v "/home/glimcb/opiproject/opi-api/storage":/defs -v "/home/glimcb/opiproject/opi-api/storage/../common/v1":/common namely/protoc-all:1.51_2 -i /common --lint -d v1alpha1 -l go -o ./v1alpha1/gen/go/  --go-source-relative
frontend_virtio_scsi.proto:170:39: Enum type "google.api.FieldBehavior" has no value named "IDENTIFIER" for option "google.api.field_behavior".
frontend_virtio_scsi.proto:190:39: Enum type "google.api.FieldBehavior" has no value named "IDENTIFIER" for option "google.api.field_behavior".
frontend_virtio_scsi.proto:216:39: Enum type "google.api.FieldBehavior" has no value named "IDENTIFIER" for option "google.api.field_behavior".
```
but we do have https://github.com/googleapis/googleapis/commit/f5987af9df625b86e23aed7218ab5f48e85e4ec8

so probably need new release of https://hub.docker.com/r/namely/protoc-all/tags

**Comment by glimchb** [comment]
merged #387 instead

**Pull request closed without merging**
