### PR TITLE
Added ObjectKey type

### PR DESCRIPTION
**Pull request by PWAlessi**
Added ObjectKey type to common protos

Signed-off-by: PWAlessi <pwalessi1@gmail.com>

### CODE REVIEW

**Comment by glimchb** [comment]
@jainvipin @llabordehpe FYI

**Comment by llabordehpe** [comment]
For this ObjectKey message, I would remove all mention of its length in the comment ("128bit (16byte)")...
The comment also indicates that the ObjectKey value is chosen by the API user (i.e. the client). it is not clear to me that it is what we want. I think it should be allocated by the API provider (i.e. the server).

**Comment by glimchb** [comment]
> 

I agree with @llabordehpe

**Comment by mestery** [comment]
> > For this ObjectKey message, I would remove all mention of its length in the comment ("128bit (16byte)")... The comment also indicates that the ObjectKey value is chosen by the API user (i.e. the client). it is not clear to me that it is what we want. I think it should be allocated by the API provider (i.e. the server).
> 
> I agree with @llabordehpe

Piling on here, but I also agree this should be allocated by the server and not the client.

**Review by glimchb — APPROVED** [review]
thanks for fixing @PWAlessi

**Pull request merged**
