### PR TITLE
Update VNIC+NVME usecase with NVMe + TCP(Local Host) + Tunnel cases

### PR DESCRIPTION
**Pull request by pathreya**
Signed-off-by: Narayana Prasad <110230547+pathreya@users.noreply.github.com>

### CODE REVIEW

**Review by glimchb — APPROVED** [review]

**Comment by glimchb** [comment]
@pathreya the image was not created using https://draw.io/ or was n ot saved as editable PNG, please fix

**Comment by pathreya** [comment]
@glimchb the diagram is generated from a dot file. I can submit it as a separate file. I will put it under images with a suffix as .dot. sounds ok?

**Comment by glimchb** [comment]
> @glimchb the diagram is generated from a dot file. I can submit it as a separate file. I will put it under images with a suffix as .dot. sounds ok?

I prefer everybody in OPI is using the same https://draw.io/

**Comment by pathreya** [comment]
@glimchb I will find a way to convert to draw.io and upload editable PNG. It might take some time since my initial efforts to do this didnt work straightaway. I will keep at it.

**Pull request merged**
