### PR TITLE
feat(storage): modify storage frontend_nvme_pcie proto file to support http api

### PR DESCRIPTION
**Pull request by chujieyang**
Define the services used by the NVMe front-end proto file in storage to support the conversion to http api.

### CODE REVIEW

**Comment by artek-koltun** [comment]
@chujieyang could you please rebase your change?

**Comment by chujieyang** [comment]
> @chujieyang could you please rebase your change?

resolved

**Comment by artek-koltun** [comment]
@chujieyang please adjust commit msg (dot is not needed at the end of the heading)
Could you also generate protobufs? Just run `make` in storage dir and commit it with `chore(storage): auto-generated protos` heading.

**Comment by artek-koltun** [comment]
@chujieyang Why did you close the PR? It could be a good starting point for community discussion

**Comment by chujieyang** [comment]
> @chujieyang Why did you close the PR? It could be a good starting point for community discussion

I will submit a pull request after redefine the proto file according to the Google AIP

**Pull request closed without merging**
