### PR TITLE
[storage][front-end] Delete xxxCreateResponse messages

### PR DESCRIPTION
**Pull request by glimchb**
Following Google [AIP-133](https://google.aip.dev/133) - Standard methods: Create

Related to #174

### CODE REVIEW

**Review by PWAlessi — APPROVED** [review]
Looks good, thanks for doing this!

**Review by mestery — APPROVED** [review]
STAMP

**Review by benlwalker — APPROVED** [review]

**Review by llabordehpe — APPROVED** [review]
Looks good.

Could this also be used to have the API provider assign the object handle,
if the API user passes in a 0-length handle in the XxxCreateRequest for example ?

**Comment by glimchb** [comment]
> Looks good.
> 
> Could this also be used to have the API provider assign the object handle, if the API user passes in a 0-length handle in the XxxCreateRequest for example ?

@llabordehpe I think so yes. AIP is talking about this here https://google.aip.dev/133#user-specified-ids and here https://google.aip.dev/155

**Comment by jainvipin** [comment]
LGTM - This change is inline with REST semantics where object itself is returned from a POST (aka create) request as mentioned [ here](https://google.aip.dev/133).

Having said the usefulness on passing the context back is desired upon failure. HTTP codes cover a full gammut of errors on the object resources as listed [here](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), but in my experience, sometimes they are not sufficient or doesn't capture the domain specific context of an error. For now let's stick to the REST semantics and then discuss later if we must return any specific return message to handle failures better.

**Review by jainvipin — APPROVED** [review]

**Comment by glimchb** [comment]
got almost all the responses, merging this now

**Pull request merged**
