### PR TITLE
[storage] QoS API proposal

### PR DESCRIPTION
**Pull request by artek-koltun**
This patch provides a proposal of API for Volume level QoS and also makes an attempt to initiate a discussion of Device level QoS.

* Volume level QoS service leverages the same approach used currently for other services.
* Device level QoS limits are provided as a part of frontend device messages, which seem to be a natural place for such limits. This needs to be contrasted with current OPI statements, which assume QoS only as part of [middleend ](https://github.com/opiproject/opi-api/blob/b6f178ec8cfa9d9aab7ddb61d154f8aa3a72faec/storage/README.md?plain=1#L84) and prescribe [object-wrapping concept](https://github.com/opiproject/opi-spdk-bridge/blob/main/doc/OPI-Storage-Sequence.png) for handling additional services.

Backend QoS shall be provided based on additional discussions.

### CODE REVIEW

**Comment by glimchb** [comment]
API call summary @sanders-mark : starting 7 days review cycle now

**Review by jainvipin — COMMENTED** [review]
Per the meeting discussion, I was under the impression that we wanted QoS limit per namespace as well, not just the controller i.e. a volume can have specific limits.

**Comment by glimchb** [comment]
> Per the meeting discussion, I was under the impression that we wanted QoS limit per namespace as well, not just the controller i.e. a volume can have specific limits.

@benlwalker @artek-koltun per @jainvipin questions: are namespace covered by `storage/v1alpha1/middleend_qos_volume.proto` or not ?

**Comment by benlwalker** [comment]
> > Per the meeting discussion, I was under the impression that we wanted QoS limit per namespace as well, not just the controller i.e. a volume can have specific limits.
> 
> @benlwalker @artek-koltun per @jainvipin questions: are namespace covered by `storage/v1alpha1/middleend_qos_volume.proto` or not ?

Yes per namespace limits mean per volume in OPI terms and they're enforced by middle-end QoS.

**Comment by artek-koltun** [comment]
> Per the meeting discussion, I was under the impression that we wanted QoS limit per namespace as well, not just the controller i.e. a volume can have specific limits.

Ben is correct.
`storage/v1alpha1/middleend_qos_volume.proto` is very similar to [encryption service](https://github.com/artek-koltun/opi-api/blob/experimental-qos-api/storage/v1alpha1/middleend_encryption.proto), which can cover namespaces as well. To create a QoS volume we need to specify original volume (namespace) to apply limits on [here](https://github.com/artek-koltun/opi-api/blob/55cfce1af72a993094c9cc6aa246bbf4a931381e/storage/v1alpha1/middleend_qos_volume.proto#L62)

**Comment by glimchb** [comment]
> Ben is correct. [storage/v1alpha1/middleend_qos_volume.proto](https://github.com/artek-koltun/opi-api/blob/experimental-qos-api/storage/v1alpha1/middleend_qos_volume.proto) is very similar to [encryption service](https://github.com/artek-koltun/opi-api/blob/experimental-qos-api/storage/v1alpha1/middleend_encryption.proto), which can cover namespaces as well. To create a QoS volume we need to specify original volume (namespace) to apply limits on [here](https://github.com/artek-koltun/opi-api/blob/55cfce1af72a993094c9cc6aa246bbf4a931381e/storage/v1alpha1/middleend_qos_volume.proto#L62)

Artek/Ben/Vipin - do we need QoS on backend volumes ? Is that the intent of the original question was ?

**Comment by jainvipin** [comment]
> > Ben is correct. [storage/v1alpha1/middleend_qos_volume.proto](https://github.com/artek-koltun/opi-api/blob/experimental-qos-api/storage/v1alpha1/middleend_qos_volume.proto) is very similar to [encryption service](https://github.com/artek-koltun/opi-api/blob/experimental-qos-api/storage/v1alpha1/middleend_encryption.proto), which can cover namespaces as well. To create a QoS volume we need to specify original volume (namespace) to apply limits on [here](https://github.com/artek-koltun/opi-api/blob/55cfce1af72a993094c9cc6aa246bbf4a931381e/storage/v1alpha1/middleend_qos_volume.proto#L62)
> 
> Artek/Ben/Vipin - do we need QoS on backend volumes ? Is that the intent of the original question was ?

usually one would limit or provide guarantees to a user/tenant/volume, backend is usually provider owned and infra should honor the user commitments ensuring backend can support what is promised to the frontend.

**Comment by jainvipin** [comment]
> > Per the meeting discussion, I was under the impression that we wanted QoS limit per namespace as well, not just the controller i.e. a volume can have specific limits.
> 
> @benlwalker @artek-koltun per @jainvipin questions: are namespace covered by `storage/v1alpha1/middleend_qos_volume.proto` or not ?

yes middle end volume qos should cover namespace... so we should be okay not adding them to the frontend protos.

The PR looks good to me!

**Comment by glimchb** [comment]
@GottliebNoam @sburla-marvell any comments ?

**Review by glimchb — APPROVED** [review]
during the API meeting the PR was approved (see recording on youtube)

**Review by sandersms — APPROVED** [review]
Approved by consensus in API workgroup meeting with comments addressed and agreed to.

**Pull request merged**
