### PR TITLE
security: IPsec protobuf definitions update

### PR DESCRIPTION
**Pull request by vijayinavolu**
Signed-off-by: Vijay Ram Inavolu <vinavolu@marvell.com>

### CODE REVIEW

**Comment by glimchb** [comment]
@vijayinavolu thanks for the contribution, please fix DCO error above... you commit must have the signed-off
see https://github.com/opiproject/opi-api/pull/129/checks?check_run_id=8493450976

**Review by mestery — CHANGES_REQUESTED** [review]
@vijayinavolu  Thanks for this PR! This seems like a parallel implementation of IPsec compared to what I have there already. Admittedly, what is there is tied very closely to strongSwan and vici. Are you proposing this parallel implementation for discussion or as something to replace what is there? This also looks very much like the Ligato implementation as well.

Also, the CI is failing for a few things, can you please fix those? I will eyeball these changes a bit closer later today, making sure no-one else merges this in the meantime.

**Comment by glimchb** [comment]
@mestery let's discuss the alignment in the API call today

**Comment by sandersms** [comment]
@vijayinavolu Can you fix the DCO for this so that we can move it forward pending the alignment with the previous IPSec contribution?

Also can you work with Kyle to address the alignment in order to get a more common IPSec definition in place?

**Comment by mestery** [comment]
Given that we have forked the [sessionOffload API](https://github.com/opiproject/sessionOffload), and it contains it's own [tunnel offloads](https://github.com/opiproject/sessionOffload/blob/main/sessionoffload/v2/tunneloffload.proto), I propose we actually close this PR and in fact remove the existing security APIs in favor of adopting the sessionOffload APIs for both session offload and tunnel (including IPsec) offload.

**Comment by glimchb** [comment]
@vijayinavolu @mestery @sandersms - what do we do with this PR ?

**Comment by mestery** [comment]
> Given that we have forked the [sessionOffload API](https://github.com/opiproject/sessionOffload), and it contains it's own [tunnel offloads](https://github.com/opiproject/sessionOffload/blob/main/sessionoffload/v2/tunneloffload.proto), I propose we actually close this PR and in fact remove the existing security APIs in favor of adopting the sessionOffload APIs for both session offload and tunnel (including IPsec) offload.

@glimchb ☝️

**Comment by sandersms** [comment]
IPSec protobufs modified on July 1, 2024 to align with CRUD model.  PR no longer valid.  Closing...

**Pull request closed without merging**
