### PR TITLE
Implementation Options for Network API Service

### PR DESCRIPTION
**Pull request by pathreya**
Implementation Options for Network API Service
A: Fully Vendor implemented
B: Partly Vendor implemented with SB implementations for popular open source entities such as OVS, VPP implemented by OPI rather than vendor. 
C: Similar to B, but makes the vendor specific code a plugin into OPI Service. It can coexist with B.

### CODE REVIEW

**Comment by glimchb** [comment]
@pathreya thank you for the contribution, any reason you decided to close this ? let me know if you need any help

**Comment by pathreya** [comment]
Hi Boris
                I got the commit message wrong. I’ve resubmitted the pull request after rectifying it.

Thanks
Prasad

From: Boris Glimcher ***@***.***>
Date: Friday, 29 July 2022 at 5:38 PM
To: opiproject/opi-api ***@***.***>
Cc: Narayana Prasad Raju Athreya ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [opiproject/opi-api] Implementation Options for Network API Service (PR #62)
External Email
________________________________

@pathreya<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pathreya&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=RCw0B_bXeBHj8OOlpjUu9zpmdF7sQ401oo770tafM-g&m=JjvbTN8I-at8tSoQqEaIYrN1WZozW9HfVaZok0E4nephY6xDaYFNXdzuwjzNSFdo&s=N8AEHjBGVgEYJtIMMPaG94h_gGEvB5esMF1x3H-2QDU&e=> thank you for the contribution, any reason you decided to close this ? let me know if you need any help

**Comment by glimchb** [comment]
@pathreya sure

next time you don't have to create new pull request, you can just `git commit --amend` and then git push again

**Comment by pathreya** [comment]
Hi Boris

Thanks for tip. I used the github fork + pull-request scheme. I was trying it for the first time and the user-fork repo ended up with the incorrect commit. So I rewrote history on the forked repo. I wasn’t sure of the connection between the pull request and changes to history on the user-fork. So I closed the pull request as a safer option.

Do you commit directly into opiproject to create pull requests? Otherwise I am not sure how I can amend commits which come from the forked tree.

Prasad

From: Boris Glimcher ***@***.***>
Date: Friday, 29 July 2022 at 5:58 PM
To: opiproject/opi-api ***@***.***>
Cc: Narayana Prasad Raju Athreya ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [opiproject/opi-api] Implementation Options for Network API Service (PR #62)
External Email
________________________________

@pathreya<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pathreya&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=RCw0B_bXeBHj8OOlpjUu9zpmdF7sQ401oo770tafM-g&m=NBRPFy-_22_EAZP8MDClegZ0ne3wkm_Sak_WlgEjM7hZL6GBYU9Gy7MFBQfibir-&s=1R5Lr6pLurCc4C0__hQEWgHFtDd4xSdJGreirZ-a50I&e=> sure

next time you don't have to create new pull request, you can just git commit --amend and then git push again

**Comment by seroyer** [comment]
No, no one should ever commit directly to the opiproject repos.  In fact
you'd find you have no authority to do so.  Once you rewrite history for
_your PR commit(s) only_ under your PR branch (via git commit --amend), you
need to force push it back to your fork:
git push -f

The PR will automatically update with the new version of the commit(s) you
amended, and add a note to the PR saying it was force pushed.

Thanks

**Comment by pathreya** [comment]
Got it.

Thanks
Prasad


________________________________
From: Steven Royer ***@***.***>
Sent: 29 July 2022 20:22
To: opiproject/opi-api ***@***.***>
Cc: Narayana Prasad Raju Athreya ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [opiproject/opi-api] Implementation Options for Network API Service (PR #62)

External Email
________________________________

No, no one should ever commit directly to the opiproject repos. In fact
you'd find you have no authority to do so. Once you rewrite history for
_your PR commit(s) only_ under your PR branch (via git commit --amend), you
need to force push it back to your fork:
git push -f

The PR will automatically update with the new version of the commit(s) you
amended, and add a note to the PR saying it was force pushed.

Thanks

**Pull request closed without merging**
